name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Rename jar
        run: mv target/*.jar target/modbusserverapp.jar

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Prepare folder on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo mkdir -p /home/ubuntu/app
          sudo chown ubuntu:ubuntu /home/ubuntu/app
          EOF

      - name: Upload jar to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/modbusserverapp.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/modbusserverapp.jar

      - name: Restart application
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl restart modbusapp
          sudo systemctl status modbusapp --no-pager
          EOF
